apiVersion: o6s.io/v1alpha1
kind: Function
metadata:
  name: nodeinfo
  namespace: openfaas-fn
spec:
  name: nodeinfo
  replicas: 2
  handler: node main.js
  image: functions/nodeinfo
  labels:
    com.openfaas.scale.min: "2"
    com.openfaas.scale.max: "8"
  environment:
    output: "verbose"
    debug: "true"
  limits:
    cpu: "200m"
    memory: "1Gi"
  requests:
    cpu: "10m"
    memory: "128Mi"
